kind: pipeline
name: default

steps:
- name: build
  image: golang:1.11.4
  commands:
    - go build

- name: slack
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook
    channel: general